# Site settings
name: 2017级16班 班级动态
email: fxzjshm@163.com
author: fxzjshm
#  url: http://fxzjshm.github.io
github: https://github.com/fxzjshm/
baseurl: "/Digital-signage"
description: 
meta_description: meta_description
# motto: 
# banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 1000

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']

github_username: fxzjshm
highlighter: rouge

# Build settings
markdown: kramdown
