# Site settings
name: 初三(1)班 电子班牌
email: fxzjshm@163.com
author: fxzjshm
url: http://fxzjshm.github.io
#  resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/fxzjshm/
baseurl: "/Digital-signage"
description: 
meta_description: meta_description
# motto: 
# banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: fxzjshm
highlighter: rouge

# Build settings
markdown: kramdown
